### ISSUE TITLE
Building this plugin against Qt 5.4 on Mac OS X (10.10.1)

### ISSUE THREAD

**Issue by minixxie** [vinipsmaker/tufao-qtcreatorplugin#3]
I'm building this plugin against Qt 5.4 on Mac 10.10.1 and got this error. The source code of qt-creator is also cloned via git as the newsest version. Please advise. Thanks. 

tufaowizard.cpp:43:19: error: use of undeclared identifier 'ProjectWizard'; did you mean 'Core::BaseFileWizardFactory::ProjectWizard'?
    setWizardKind(ProjectWizard);
                  ^~~~~~~~~~~~~
                  Core::BaseFileWizardFactory::ProjectWizard

../../qt-creator/src/plugins/coreplugin/iwizardfactory.h:55:9: note: 'Core::BaseFileWizardFactory::ProjectWizard' declared here
        ProjectWizard = 0x04
        ^
tufaowizard.cpp:43:5: error: use of undeclared identifier 'setWizardKind'; did you mean 'Core::BaseFileWizardFactory::setWizardKind'?
    setWizardKind(ProjectWizard);
    ^~~~~~~~~~~~~
    Core::BaseFileWizardFactory::setWizardKind
../../qt-creator/src/plugins/coreplugin/iwizardfactory.h:78:10: note: 'Core::BaseFileWizardFactory::setWizardKind' declared here
    void setWizardKind(WizardKind kind) { m_kind = kind; }
         ^
tufaowizard.cpp:43:5: error: call to non-static member function without an object argument
    setWizardKind(ProjectWizard);
    ^~~~~~~~~~~~~
tufaowizard.cpp:44:5: error: use of undeclared identifier 'setIcon'; did you mean 'Core::BaseFileWizardFactory::setIcon'?
    setIcon(QIcon(QString::fromUtf8(":/icon.png")));
    ^~~~~~~
    Core::BaseFileWizardFactory::setIcon
../../qt-creator/src/plugins/coreplugin/iwizardfactory.h:79:10: note: 'Core::BaseFileWizardFactory::setIcon' declared here
    void setIcon(const QIcon &icon) { m_icon = icon; }
         ^
tufaowizard.cpp:44:5: error: call to non-static member function without an object argument
    setIcon(QIcon(QString::fromUtf8(":/icon.png")));
    ^~~~~~~
tufaowizard.cpp:45:5: error: use of undeclared identifier 'setDisplayName'; did you mean 'Core::BaseFileWizardFactory::setDisplayName'?
    setDisplayName(QString::fromUtf8("Tufão Web Server"));
    ^~~~~~~~~~~~~~
    Core::BaseFileWizardFactory::setDisplayName
../../qt-creator/src/plugins/coreplugin/iwizardfactory.h:81:10: note: 'Core::BaseFileWizardFactory::setDisplayName' declared here
    void setDisplayName(const QString &displayName) { m_displayName = displayName; }
         ^
tufaowizard.cpp:45:5: error: call to non-static member function without an object argument
    setDisplayName(QString::fromUtf8("Tufão Web Server"));
    ^~~~~~~~~~~~~~
tufaowizard.cpp:46:5: error: use of undeclared identifier 'setId'
    setId(QString::fromUtf8(Tufao::Constants::TUFAO_WIZARD_ID));
    ^
tufaowizard.cpp:47:5: error: use of undeclared identifier 'setDescription'; did you mean 'Core::BaseFileWizardFactory::setDescription'?
    setDescription(QString::fromUtf8("Creates a Tufão web server project."));
    ^~~~~~~~~~~~~~
    Core::BaseFileWizardFactory::setDescription
../../qt-creator/src/plugins/coreplugin/iwizardfactory.h:80:10: note: 'Core::BaseFileWizardFactory::setDescription' declared here
    void setDescription(const QString &description) { m_description = description; }
         ^
tufaowizard.cpp:47:5: error: call to non-static member function without an object argument
    setDescription(QString::fromUtf8("Creates a Tufão web server project."));
    ^~~~~~~~~~~~~~
tufaowizard.cpp:49:5: error: use of undeclared identifier 'setCategory'; did you mean 'Core::BaseFileWizardFactory::setCategory'?
    setCategory(QString::fromUtf8(Constants::TUFAO_WIZARD_CATEGORY));
    ^~~~~~~~~~~
    Core::BaseFileWizardFactory::setCategory
../../qt-creator/src/plugins/coreplugin/iwizardfactory.h:82:10: note: 'Core::BaseFileWizardFactory::setCategory' declared here
    void setCategory(const QString &category) { m_category = category; }
         ^
tufaowizard.cpp:49:5: error: call to non-static member function without an object argument
    setCategory(QString::fromUtf8(Constants::TUFAO_WIZARD_CATEGORY));
    ^~~~~~~~~~~
tufaowizard.cpp:51:5: error: use of undeclared identifier 'setDisplayCategory'; did you mean
      'Core::BaseFileWizardFactory::setDisplayCategory'?
    setDisplayCategory(trUtf8(Constants::TUFAO_WIZARD_TR_CATEGORY));
    ^~~~~~~~~~~~~~~~~~
    Core::BaseFileWizardFactory::setDisplayCategory
../../qt-creator/src/plugins/coreplugin/iwizardfactory.h:83:10: note: 'Core::BaseFileWizardFactory::setDisplayCategory' declared here
    void setDisplayCategory(const QString &displayCategory) { m_displayCategory = displayCategory; }
         ^
tufaowizard.cpp:51:5: error: call to non-static member function without an object argument
    setDisplayCategory(trUtf8(Constants::TUFAO_WIZARD_TR_CATEGORY));
    ^~~~~~~~~~~~~~~~~~
tufaowizard.cpp:41:35: warning: unused parameter 'parent' [-Wunused-parameter]
TufaoWizard::TufaoWizard(QObject *parent)
                                  ^
tufaowizard.cpp:64:15: error: unknown type name 'WizardPageList'; did you mean 'Core::WizardDialogParameters::WizardPageList'?
        const WizardPageList &
              ^~~~~~~~~~~~~~
              Core::WizardDialogParameters::WizardPageList
../../qt-creator/src/plugins/coreplugin/basefilewizardfactory.h:61:34: note: 'Core::WizardDialogParameters::WizardPageList' declared here
    typedef QList<QWizardPage *> WizardPageList;
                                 ^
tufaowizard.cpp:67:29: error: no member named 'applyExtensionPageShortTitle' in 'Core::BaseFileWizard'
            BaseFileWizard::applyExtensionPageShortTitle(wizard,
            ~~~~~~~~~~~~~~~~^
1 warning and 16 errors generated.

**Comment by vinipsmaker** [comment]
QtCreator plugin system breaks API **every** release. Are you using the latest released stable QtCreator?

> The source code of qt-creator is also cloned via git as the newsest version

Which version is that?

**Comment by minixxie** [comment]
Thanks and I forgot to checkout the specific tag. Now it solved.
