### ISSUE TITLE
Project created by Tufao creator plugin: compile error

### ISSUE THREAD

**Issue by minixxie** [vinipsmaker/tufao-qtcreatorplugin#4]
Hi,

<pre>
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++ -Wall -W -fPIE -DTUFAO_VERSION_MAJOR=1 -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/local/Cellar/qt5/5.4.0/mkspecs/macx-clang -I../TestTufao -I/usr/include/tufao-1 -I/usr/local/Cellar/qt5/5.4.0/lib/QtNetwork.framework/Versions/5/Headers -I/usr/local/Cellar/qt5/5.4.0/lib/QtCore.framework/Versions/5/Headers -I. -I. -F/usr/local/Cellar/qt5/5.4.0/lib -o main.o ../TestTufao/main.cpp
../TestTufao/main.cpp:3:10: fatal error: 'Tufao/HttpPluginServer' file not found
#include <Tufao/HttpPluginServer>
         ^
1 error generated.
</pre>
The generated main() is:
<pre>
#include &lt;QCoreApplication&gt;

#include &lt;Tufao/HttpPluginServer&gt;
#include &lt;Tufao/HttpFileServer&gt;
#include &lt;Tufao/NotFoundHandler&gt;
#include &lt;Tufao/HttpServerRequestRouter&gt;
#include &lt;Tufao/HttpServer&gt;

using namespace Tufao;

int main(int argc, char *argv[])
{
	QCoreApplication a(argc, argv);

	HttpPluginServer plugins{"routes.json"};

	HttpServerRequestRouter router{
		{QRegularExpression{""}, plugins},
		{QRegularExpression{""}, HttpFileServer::handler("public")},
		{QRegularExpression{""}, NotFoundHandler::handler()}
	};

	HttpServer server;

	QObject::connect(&server, &HttpServer::requestReady,
					 &router, &HttpServerRequestRouter::handleRequest);

	server.listen(QHostAddress::Any, 8080);

	return a.exec();
}
</pre>

While when I search for the class HttpPluginServer, it cannot be found even in the whole tufao source tree. I guess it was a previous design that no longer be used now?

Thanks & Regards,
Simon

**Comment by vinipsmaker** [comment]
You aren't using a stable Tufão release. Use one of the released Tufão versions.

**Comment by minixxie** [comment]
Thanks. Also, I should choose "default" rather than "application" when I'm creating a new project from template. That gave me a simpler example.
